#+TITLE: Senior Principal Scientist
#+AUTHOR: Fred K. Gruber
#+email: fgruber@ieee.org
# CV theme - options include: 'casual' (default), 'classic', 'oldstyle' and 'banking'
#+CVSTYLE: classic
# CV color - options include: 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
#+CVCOLOR: blue
#+LATEX_HEADER:\usepackage[scale=0.75]{geometry}
#+LATEX_HEADER:\usepackage[T1]{fontenc}
#+LATEX_HEADER:\usepackage{lmodern}
#+LATEX_HEADER:\usepackage[sorting=ydnt,minnames=5,minbibnames=5,maxbibnames=5,backref=true]{biblatex}
#+LATEX_HEADER:\usepackage{multicol}
#+ADDRESS: Newton, MA
#+MOBILE: (+1) 617-784-1265
#+LINKEDIN: fredgruber
#+homepage: www.fredgruber.org


* Summary
:PROPERTIES:
:CV_ENV:   cvhonor
:END:

With 10 years of experience in analyzing medical datasets from clinical and real-world sources, I have a proven track record in the investigation of prognostic and predictive biomarkers as well as drug target discovery. I am proficient in all stages of data analysis, from preprocessing to modeling and interpretation, and have successfully led multiple projects with top pharmaceutical scientists as stakeholders. My expertise lies in statistical and machine learning models applied to medical data, with a focus on causal methods, high-dimensional variable selection, data integration, and interpretability. I am skilled in working with multi-modal high-dimensional genomic data and clinical variables, utilizing techniques such as bayesian networks, logistic regression, survival analysis, neural networks, and more. Additionally, I am the developer and maintainer of multiple internal R packages for data preprocessing, visualization, machine learning, and analysis as well as maintainer of the simcausal R package for simulation of causal networks.

* Professional Experience
:PROPERTIES:
:CV_ENV: cvemployer
:END:
** Senior Principal Scientist
:PROPERTIES:
:CV_ENV: cventry
:FROM:   <2018-08-01>
:TO:     current
:LOCATION: Somerville, MA
:EMPLOYER: Aitia
:END:

- Analysis of high-dimensional multi-modal biological data.
- Experience with RNAseq, simple nucleotides variants, structural variants, copy number variants, and clinically relevant variables.
- Focus on discovering biomarkers and drug targets for different diseases.
- Experience in analyzing oncological datasets for lung cancer, multiple myeloma, prostate cancer, pancreatic cancer, and kidney cancer.
- Utilization of different data sources such as TCGA/GDC, Flatiron, ICGC, Tempus MMRF, and others.
- Involvement in all stages of the analysis process, from data preprocessing to model construction and interpretation as well as presentation to clients.
- Use of proprietary causal Bayesian network learning and predictive tools as main tools.
- Exploration of open source machine learning techniques applicable to datasets.
- Investigation of unsupervised machine learning methods for tumor subclonal composition analysis and patient drug response stratification.
- Developed the best performing model predicting high-risk multiple myeloma in the Multiple Myeloma DREAM Challenge finding a novel expression-based risk marker, PHF19, which was further validated in vitro and published in journal Leukemia.

*** source :noexport:
** Principal Scientist
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2016-10-01>
:TO:     <2018-10-01>
:LOCATION: Cambridge, MA
:EMPLOYER: Aitia
:END:
- Responsible for the development of causal network models for multiple myeloma based on multiple iterations of the CoMMPass MMRF  dataset.
- Developed preprocessing pipelines to prepare diverse data modalities including copy number variants, structural variants, single nucleotide variants, gene expression, and clinical data.
- Validation of result by literature search.
- Published multiple peer-reviewed conference papers in a major blood cancer conference.
** Senior Systems Biologist
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2013-07-01>
:TO:     <2016-10-01>
:LOCATION: Cambridge, MA
:EMPLOYER: Aitia
:END:
- Developed, implemented, and benchmarked algorithms for the prediction of rare adverse events on patients taking the client's drug.
- Developed novel algorithms implementing variations of logistic regression that perform better under imbalanced outcomes.
- Comparative analysis using 17 public-domain datasets
- Applied to the client's clinical and genomic multiple sclerosis dataset.
- Successfully delivered R package with new algorithm.
- Success of algorithm lead to production code in the internal causal and predictive tools at Aitia.
- Developed predictive and causal models of Chron's disease for the purpose of elucidading the relationships between TL1A, DR3,	IFNgamma, and a	variety	of genetic, gene expression, immune response, and clinical variables from tissue samples.

** Postdoctoral Scientist
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2009-05-01>
:TO:     <2013-06-01>
:LOCATION: Cambridge, MA
:EMPLOYER: Schlumberger-Doll Reasearch Center
:END:
- Designed, implemented, and tested algorithms for analyzing Nuclear Magnetic Resonance measurements for oil exploration
- Utilized Matlab extensively for research purposes
- Utilized Python for production code integration with company software
- Worked with optimization algorithms, sparse coding, regularization, and general machine learning tools.

* Education
:PROPERTIES:
:CV_ENV: cvschool
:END:
** Ph.D., Electrical engineering
:PROPERTIES:
:CV_ENV: cventry
:EMPLOYER: Northeastern University
:LOCATION: Boston, MA
:FROM: 2004
:TO: 2009
:END:
- Research Assistant at Northeastern University's Communications and Digital Signal Processing Center.
- Member of the Honor Society of Eta Kappa Nu.
- GPA of 3.9/4.0
- Developed algorithms for the determination of the location of objects from the measure of scattered fields. This is a fundamental problem in the area of remote sensing and inverse problems. Also studied the fundamental limits of communication using electromagnetic fields.

** Master of science, Industrial Engineering and Management Systems
:PROPERTIES:
:CV_ENV: cventry
:employer: University of Central Florida
:LOCATION: Orlando, FL
:FROM: 2003
:TO: 2004
:END:
- Research Assistant the Center for NASA Simulation Research.
- Phi Kappa Phi honor society
- GPA of 3.9/4.0
- Recipient of the University of Central Florida's Graduate Merit Fellowship Award, 2004
- Worked at the NASA Simulation Research Group and was involved in the design of an advanced simulation of the probability of failure a space shuttle during reentry and launch.
- For my master thesis, I developed a Genetic Algorithm in C++ for the optimal selection of the parameters of a Support Vector Machine. Published this work in book chapter.

** Bachelors, Electrical and Electronic Engineering
:PROPERTIES:
:CV_ENV: cventry
:employer: Universidad Tecnológica de Panamá
:LOCATION: Panamá City, Panamá
:FROM: 1998
:TO: 2003
:END:
- Member of IEEE
- GPA of 3.74/4.0
- Honor Scholarship for undergraduate studies in Engineering at the Technological University of Panama, 1998 - 2002.
- Gold Medal "Guillermo Andreve" for educational achievements, Panama, 1997.

* Relevant Certificates
:PROPERTIES:
:CV_ENV: cvschool
:END:

** Combining information for Causal Inference
:PROPERTIES:
:CV_ENV: cventry
:employer: Harvard T.H. Chan School of Public Health
:LOCATION: Cambridge, MA
:FROM: 2023
:TO: 2023
:END:

** Target Trial Emulation
:PROPERTIES:
:CV_ENV: cventry
:employer: Harvard T.H. Chan School of Public Health
:LOCATION: Cambridge, MA
:FROM: 2022
:TO: 2022
:END:


** Applied Deep Learning Boot Camp
:PROPERTIES:
:CV_ENV: cventry
:employer: MIT Professional School
:LOCATION: Cambridge, MA
:FROM: 2020
:TO: 2020
:END:

** An Introduction to Causal Inference
:PROPERTIES:
:CV_ENV: cventry
:employer: Harvard T.H. Chan School of Public Health
:LOCATION: Cambridge, MA
:FROM: 2018
:TO: 2018
:END:

** Data Science: Data to insights
:PROPERTIES:
:CV_ENV: cventry
:employer: MIT Professional School
:LOCATION: Cambridge, MA
:FROM: 2016
:TO: 2016
:END:

* Skills
:PROPERTIES:
:CV_ENV:   cvskills
:END:
\begin{multicols}{2}
\begin{itemize}
\item R
\item ggplot2
\item shiny
\item python
\item matlab
\item elisp
\item machine learning
\item causal discovery
\item causal inference
\item python
\item High-dimensional data analysis
\item AWS
\item data wrangling
\item data analysis
\item data visualization
\item statistics
\item teamwork
\item scientific presentation
\item research
\end{itemize}
\end{multicols}


* Languages
- *English* Fluent
- *Spanish* Native


* Selected Publications :ignore:
\begin{refsection}[resume.bib]
\nocite{*}
\bibliographystyle{ieee}
\printbibliography[title={Selected Publications}]
\end{refsection}


* export :noexport:
#+begin_src elisp
(org-export-to-file 'moderncv "resume_sept_2023_takeda.tex")
(org-latex-compile "resume_sept_2023_takeda.tex")
#+end_src

#+RESULTS:
: /Users/fred/Documents/gitRepos/general-functions/personal/resume_sept_2023_takeda.pdf
* job prospect :noexport:
https://jobs.takeda.com/job/cambridge/principal-computational-and-systems-biology-c-and-sb-scientist/1113/50649334096
#+begin_src org

Join Takeda as a Principal Computational and Systems Biology (C&SB) Scientist and become part of a multi-disciplinary drug discovery group with a mission to provide innovative therapies for GI diseases, including inflammatory bowel disease and chronic liver disorders. You will contribute to projects from early discovery to clinical development by designing and leading in silico strategies, and executing on biomarker and translational data analysis plans. You will be an integral collaborator in large-scale multi-omics data studies with internal groups, CROs, and academic partners. As part of the Gastroenterology Drug Discovery Unit (GI DDU) team, you will report to a Computational Biology Group leader and engage with key stakeholders including biologists, data science and engineering groups, translational medicine, and biomarker teams.


How you will contribute:
Be a subject matter expert in projects requiring genomic and high-dimensional data analyses.
Be a scientific consultant or as manager of a matrix project team; formulate and lead data analysis strategies with internal or external resources and ensure milestones, deliverables are met regarding timelines and expectations of data quality.
Perform multi-omics and multi-modal data integration to identify molecular predictors, inform pathway/target mechanism of action, and achieve translational medicine goals.
Design and apply computational methods to analyze, integrate, visualize, and interpret bulk and single cell readouts (scRNA-Seq, snRNA-Seq, CyTOF), proteomics, metabolomics, epigenomics, and spatial tissue profiling datasets.
Present scientific reports in internal meetings in all settings and with participants of all levels of the organization, and for external audiences.
Establish partnership with and maintain a collaborative, integrated role with project teams to influence the experimental design, assays needed, data generation, analysis, integration, and interpretation.
Proactively identify complex obstacles, recommend and implement solutions using a diverse set of resources.
Work with data and quantitative scientists and data engineering groups to enhance our computational infrastructure, build on innovative C&SB solutions and intuitive multi-omics interface.
Independently design, develop, and execute research assignments contributing to multiple projects.
Participate in due diligences of external opportunities when needed.
Collaborate and communicate with colleagues effectively, performing as a role model supporting Takeda culture.
Minimum Requirements/Qualifications:
Ph.D. degree in a scientific discipline with 6+ years experience.
Previous industry experience and a strong background in applying computational and systems biology to research, translational and clinical programs with demonstrated ability to meet program objectives and timelines.
Proven leadership experience of multi-part and complex computational or systems biology projects.
Strong organizational and effective communication skills.
Strong knowledge, experience, and scientific understanding of molecular biology and genomics.
Biological knowledge in one or more areas of inflammation, inflammatory bowel disease, or liver and gut fibrosis.
Demonstrated ability to independently solve scientific problems using multiple, state-of-the-art technologies and approaches.
Demonstrated experience in large-scale multi-omics (e.g. bulk or single-cell, spatial sequencing, proteomics, epigenetics, and more), multi-modal data integration, network analysis, and meta-analyses.
Proficiency with machine learning is preferred.
Proficiency with computational method evaluation, development, and implementation.
Solid knowledge of Unix/Linux, command line interfaces, and fluency in some common scripting and/or programming language (e.g., R, Python, Perl, Java, C / C++) used for statistical and computational multi-omics analysis.
Familiarity with popular public domain data sources and programmatic interfaces.
Familiarity with high performance computing, relational databases (e.g., SQL), and cloud computing or distributed computing (Amazon Web Services).
What Takeda can offer you:
Comprehensive Healthcare: Medical, Dental, and Vision
Financial Planning & Stability: 401(k) with company match and Annual Retirement Contribution Plan
Health & Wellness programs including onsite flu shots and health screenings
Generous time off for vacation and the option to purchase additional vacation days
Community Outreach Programs and company match of charitable contributions
Family Planning Support
Flexible Ways of Working
Tuition reimbursement
#+end_src
** AI talk
#+begin_ai
I'm interested in the following job:
Join Takeda as a Principal Computational and Systems Biology (C&SB) Scientist and become part of a multi-disciplinary drug discovery group with a mission to provide innovative therapies for GI diseases, including inflammatory bowel disease and chronic liver disorders. You will contribute to projects from early discovery to clinical development by designing and leading in silico strategies, and executing on biomarker and translational data analysis plans. You will be an integral collaborator in large-scale multi-omics data studies with internal groups, CROs, and academic partners. As part of the Gastroenterology Drug Discovery Unit (GI DDU) team, you will report to a Computational Biology Group leader and engage with key stakeholders including biologists, data science and engineering groups, translational medicine, and biomarker teams.

How you will contribute:
Be a subject matter expert in projects requiring genomic and high-dimensional data analyses.
Be a scientific consultant or as manager of a matrix project team; formulate and lead data analysis strategies with internal or external resources and ensure milestones, deliverables are met regarding timelines and expectations of data quality.
Perform multi-omics and multi-modal data integration to identify molecular predictors, inform pathway/target mechanism of action, and achieve translational medicine goals.
Design and apply computational methods to analyze, integrate, visualize, and interpret bulk and single cell readouts (scRNA-Seq, snRNA-Seq, CyTOF), proteomics, metabolomics, epigenomics, and spatial tissue profiling datasets.
Present scientific reports in internal meetings in all settings and with participants of all levels of the organization, and for external audiences.
Establish partnership with and maintain a collaborative, integrated role with project teams to influence the experimental design, assays needed, data generation, analysis, integration, and interpretation.
Proactively identify complex obstacles, recommend and implement solutions using a diverse set of resources.
Work with data and quantitative scientists and data engineering groups to enhance our computational infrastructure, build on innovative C&SB solutions and intuitive multi-omics interface.
Independently design, develop, and execute research assignments contributing to multiple projects.
Participate in due diligences of external opportunities when needed.
Collaborate and communicate with colleagues effectively, performing as a role model supporting Takeda culture.
Minimum Requirements/Qualifications:
Ph.D. degree in a scientific discipline with 6+ years experience.
Previous industry experience and a strong background in applying computational and systems biology to research, translational and clinical programs with demonstrated ability to meet program objectives and timelines.
Proven leadership experience of multi-part and complex computational or systems biology projects.
Strong organizational and effective communication skills.
Strong knowledge, experience, and scientific understanding of molecular biology and genomics.
Biological knowledge in one or more areas of inflammation, inflammatory bowel disease, or liver and gut fibrosis.
Demonstrated ability to independently solve scientific problems using multiple, state-of-the-art technologies and approaches.
Demonstrated experience in large-scale multi-omics (e.g. bulk or single-cell, spatial sequencing, proteomics, epigenetics, and more), multi-modal data integration, network analysis, and meta-analyses.
Proficiency with machine learning is preferred.
Proficiency with computational method evaluation, development, and implementation.
Solid knowledge of Unix/Linux, command line interfaces, and fluency in some common scripting and/or programming language (e.g., R, Python, Perl, Java, C / C++) used for statistical and computational multi-omics analysis.
Familiarity with popular public domain data sources and programmatic interfaces.
Familiarity with high performance computing, relational databases (e.g., SQL), and cloud computing or distributed computing (Amazon Web Services).

Need  your help on my application
Dear Hiring Manager,

I am writing to express my interest in the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda. The opportunity to contribute to the development of innovative therapies for GI diseases aligns perfectly with my background and career goals.

With a Ph.D. degree in a scientific discipline and over 6 years of industry experience, I have developed a strong foundation in computational and systems biology. Throughout my career, I have successfully led and managed complex projects, meeting program objectives and timelines. My expertise lies in applying computational methods to analyze genomic and high-dimensional data, integrating multi-omics datasets, and identifying molecular predictors. I am skilled in utilizing various technologies and approaches, including bulk and single-cell sequencing, proteomics, epigenetics, and more.

I am highly proficient in statistical and computational multi-omics analysis, with fluency in programming languages such as R, Python, Perl, Java, and C/C++. Additionally, I have experience with machine learning and have implemented computational methods for data evaluation and development. My knowledge of Unix/Linux, command line interfaces, and familiarity with cloud computing and relational databases further enhances my capabilities in data analysis and interpretation.

In my previous roles, I have collaborated effectively with multidisciplinary teams, including biologists, data science and engineering groups, translational medicine, and biomarker teams. I am skilled in presenting scientific reports to various audiences and have consistently demonstrated exceptional organizational and communication skills.

I am particularly excited about the opportunity to work within the Gastroenterology Drug Discovery Unit and make a meaningful impact in the field of GI diseases. Takeda's commitment to scientific excellence and innovation aligns with my own values, and I am eager to contribute to the company's mission.

Thank you for considering my application. I am thrilled at the prospect of joining Takeda and becoming an integral part of the Computational Biology Group. I look forward to the opportunity to discuss how my skills and experience align with your needs in more detail.

Sincerely,

[Your Name]

[ME]:  Help me improve the following resume summary:
10 years of experience in analyzing medical datasets from clinical and real world sources for multiple diseases with the goal of determining prognostic and predictive  biomarker, risk prediction, and drug target discovery. Proficient in data preprocessing, model creation, and model interpretation. Lead multiple projects from data preparation to modeling to presentation of the results to stakeholders (external scientists from top pharmaceuticals). Strong interest in the development of statistical and machine learning models applied to medical data, with a focus on causal methods, high dimensional variable selection, data integration, and interpretability. Skilled in working with multi-modal high-dimensional genomic data and clinical variables. Proficient in various techniques such as bayesian networks, variable selection methods, causal discovery, logistic regression, survival analysis, neural networks, support vector machines, genetic algorithms, statistical signal processing, inverse problem theory, sparse coding, and simulation and modeling. Develop and maintain 4 R packages for internal use in data preprocessing, visualization, machine learning, and analysis and maintain simcausal R package for simulation of causal networks.
Summary:
With 10 years of experience in analyzing medical datasets from clinical and real-world sources, I have a proven track record in determining prognostic and predictive biomarkers and discovering drug targets. I am proficient in all stages of data analysis, from preprocessing to modeling and interpretation, and have successfully led multiple projects with top pharmaceutical scientists as stakeholders. My expertise lies in statistical and machine learning models applied to medical data, with a focus on causal methods, high-dimensional variable selection, data integration, and interpretability. I am skilled in working with multi-modal high-dimensional genomic data and clinical variables, utilizing techniques such as bayesian networks, logistic regression, survival analysis, neural networks, and more. Additionally, I am the developer and maintainer of multiple R packages for data preprocessing, visualization, machine learning, and analysis. I am confident that my skills and experience make me an exceptional fit for the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda.

[ME]: given the job offer and my experience can you write an appropriate cover letter for the application?
[Your Name]
[Your Address]
[City, State ZIP Code]
[Email Address]
[Phone Number]
[Today's Date]

[Recipient's Name]
[Recipient's Job Title]
[Takeda Pharmaceuticals]
[Company Address]
[City, State ZIP Code]

Dear [Recipient's Name],

I am writing to express my strong interest in the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda Pharmaceuticals. With my extensive experience in analyzing medical datasets and discovering biomarkers and drug targets, I am confident in my ability to contribute to Takeda's mission of providing innovative therapies for GI diseases.

Over the course of my 10-year career, I have demonstrated expertise in analyzing medical datasets from clinical and real-world sources with the goal of determining prognostic and predictive biomarkers and identifying potential drug targets. I have successfully led multiple projects, from data preprocessing to modeling and interpretation, collaborating with external scientists from top pharmaceutical companies. My skills in statistical and machine learning models, including causal methods, high-dimensional variable selection, and data integration, have allowed me to generate meaningful insights and actionable results.

I am particularly intrigued by Takeda's focus on computational and systems biology in the development of therapies for GI diseases, including inflammatory bowel disease and chronic liver disorders. My experience in working with multi-modal high-dimensional genomic data and clinical variables aligns directly with the challenges and objectives of this role. I believe that my proficiency in techniques such as bayesian networks, logistic regression, survival analysis, neural networks, and more, along with my expertise in developing and maintaining R packages for data analysis and machine learning, make me a strong fit for this position.

Furthermore, Takeda's commitment to scientific excellence and innovation resonates with my own values. I am eager to contribute to Takeda's mission and collaborate with a diverse team of experts in biologists, data science and engineering groups, translational medicine, and biomarker teams. I am confident that my strong organizational and communication skills will enable effective collaboration and presentation of scientific findings to stakeholders at all levels of the organization.

Thank you for considering my application for the Principal Computational and Systems Biology (C&SB) Scientist position. I am excited about the possibility of joining Takeda Pharmaceuticals and making a meaningful impact in the field of GI diseases. I would welcome the opportunity to discuss how my skills and experience align with the needs of the organization in more detail.

Please find attached my resume for your review. I look forward to the opportunity of discussing my application further and demonstrating why I am an excellent fit for this position.

Thank you for your time and consideration.

Sincerely,

[Your Name]

[ME]: given the job offer and my experience can you write an appropriate cover email for the application?
Dear Hiring Manager,

I am writing to apply for the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda. With my extensive experience in analyzing medical datasets and discovering biomarkers and drug targets, I am confident that I would make a valuable contribution to Takeda's mission of providing innovative therapies for GI diseases.

Over the past 10 years, I have been involved in analyzing medical datasets from clinical and real-world sources to determine prognostic and predictive biomarkers and identify potential drug targets. I have successfully led multiple projects, collaborating with external scientists from top pharmaceutical companies, and demonstrating expertise in statistical and machine learning models, including causal methods, high-dimensional variable selection, and data integration. My skills in techniques such as bayesian networks, logistic regression, survival analysis, neural networks, and more, combined with my proficiency in developing and maintaining R packages for data analysis and machine learning, make me a strong fit for this role.

I am particularly excited about the opportunity to work with Takeda in the field of computational and systems biology for GI diseases, including inflammatory bowel disease and chronic liver disorders. My experience in working with multi-modal high-dimensional genomic data and clinical variables aligns directly with the challenges and objectives of this role. I am confident that my skills and expertise would enable me to generate meaningful insights and actionable results.

Takeda's commitment to scientific excellence and innovation aligns with my own values, and I am eager to contribute to the organization's mission. I am confident in my ability to collaborate effectively with a diverse team of experts, including biologists, data science and engineering groups, translational medicine, and biomarker teams. My strong organizational and communication skills would allow for effective collaboration and presentation of scientific findings to stakeholders at all levels of the organization.

Thank you for considering my application for the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda. I have attached my resume for your review and would welcome the opportunity to discuss my application further. I am excited about the possibility of joining Takeda Pharmaceuticals and making a meaningful impact in the field of GI diseases.

Thank you for your time and consideration.

Sincerely,

[Your Name]

[ME]: 
#+end_ai

** cover letter :noexport:

Dear Hiring Manager,

I am writing to apply for the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda. With my extensive experience in analyzing medical datasets for the discovery of biomarkers and drug targets, I am confident that I would make a valuable contribution to Takeda's mission of providing innovative therapies for GI diseases.

Over the past 10 years, I have been involved in analyzing medical datasets from clinical and real-world sources to determine prognostic and predictive biomarkers and identify potential drug targets. I have successfully led multiple projects, collaborating with external scientists from top pharmaceutical companies, and demonstrating expertise in statistical and machine learning models, including causal methods, high-dimensional variable selection, and data integration. My skills in techniques such as bayesian networks, logistic regression, survival analysis, neural networks, and more, combined with my proficiency in developing and maintaining R packages for data analysis and machine learning, make me a strong fit for this role.

I am particularly excited about the opportunity to work with Takeda in the field of computational and systems biology for GI diseases. My experience in working with multi-modal high-dimensional genomic data and clinical variables aligns directly with the challenges and objectives of this role. I am confident that my skills and expertise would enable me to generate meaningful insights and actionable results.

Takeda's commitment to scientific excellence and innovation aligns with my own values, and I am eager to contribute to the organization's mission. I am confident in my ability to collaborate effectively with a diverse team of experts, including biologists, data science and engineering groups, translational medicine, and biomarker teams. My strong organizational and communication skills would allow for effective collaboration and presentation of scientific findings to stakeholders at all levels of the organization.

Thank you for considering my application for the Principal Computational and Systems Biology (C&SB) Scientist position at Takeda. I have attached my resume for your review and would welcome the opportunity to discuss my application further. I am excited about the possibility of joining Takeda Pharmaceuticals and making a meaningful impact in the field of GI diseases.

Thank you for your time and consideration.

Sincerely,

[Your Name]

** Contact :noexport:
Shun-Chiao
https://www.linkedin.com/in/shun-chiao-chang-86358823/

Hi Shun-Chiao,

how are you?

I was thinking of applying for a Principal Computational and Systems Biology Scientist job posting I saw and would love to hear from your experience at Takeda sometime.

By the way do you do referrals at Takeda?

thanks
Fred
